require('lsp.config')

vim.lsp.enable('gopls')
vim.lsp.enable('clangd')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('pyright')
vim.lsp.enable('ts_ls')
vim.lsp.enable('jdtls')
vim.lsp.enable('lua_ls')
vim.lsp.enable('wgsl_analyzer')
vim.lsp.enable('csharp_ls')
-- vim.lsp.enable('omnisharp')
vim.lsp.enable('angularls')
-- vim.lsp.enable('kotlin_language_server')
vim.lsp.enable('cssls')
