require('lsp.config')

vim.lsp.enable('clangd')
vim.lsp.enable('pyright')
vim.lsp.enable('ts_ls')
vim.lsp.enable('jdtls')
vim.lsp.enable('lua_ls')
vim.lsp.enable('csharp_ls')
vim.lsp.enable('cssls')
vim.lsp.enable('yamlls')
vim.lsp.enable('tailwindcss')
