require('plugins/nvim-treesitter')
require('plugins/nvim-devicons')
require('plugins/kanagawa')
require('plugins/telescope')
require('plugins/autoclose')
require('plugins/nvim-ts-autotag')
require('plugins/neo-tree')
require('plugins/oil')
require('plugins/avante')
require('plugins/snacks')

vim.cmd('colorscheme kanagawa-dragon')
