require('plugins/nvim-treesitter')
require('plugins/nvim-devicons')
require('plugins/kanagawa')
require('plugins/telescope')
require('plugins/autoclose')
require('plugins/nvim-ts-autotag')
vim.cmd('colorscheme kanagawa-dragon')
